mongo:
  address: ds121716.mlab.com
  dbName: ketu
  password: Yashpandey@123
  port: 21716
  userName: ketu_dev_user

management:
  endpoint:
    health:
      enabled: true
     
  
spring:
  servlet:
    multipart:
      max-file-size: 10MB
