mongo:
  address: cluster0.ronz5.mongodb.net
  dbName: myFirstDatabase
  password: killjangofat
  port: 57648
  userName: yash

management:
  endpoint:
    health:
      enabled: true
     
  
spring:
  servlet:
    multipart:
      max-file-size: 10MB
