mongo:
  address: ds257648.mlab.com
  dbName: ketu
  password: Yashpandey@123
  port: 57648
  userName: ketu_dev_user

management:  endpoint:    health:      enabled: true
     
  
spring:  servlet:    multipart:      max-file-size: 10MB